text_field:
  base: "block w-full border rounded-md py-2 px-3 focus:outline-none dark:bg-gray-700/50 dark:border-gray-500 dark:text-gray-300 dark:placeholder-gray-400 dark:focus:ring-gray-500 dark:focus:ring-2 dark:focus:border-transparent"
  valid: "border-gray-300 focus:ring-blue-600 focus:border-blue-600"
  invalid: "pr-10 border-red-300 text-red-900 placeholder-red-300 focus:ring-red-500 focus:border-red-500"
label:
  base: "block text-sm font-medium text-gray-700 dark:text-gray-200"
error_field:
  base: "mt-2 text-sm text-red-600 dark:text-red-500"
  visible: ""
  hidden: "hidden"
